#!/bin/bash
#
# Install the blacklistd programs and configuration
#
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run by root"
    exit 1
fi

if ! command -v logsurfer
then
  echo "logsurfer not found"
  echo "install logsurfer and try again"
  exit 1
fi

if ! command -v nft
then
  echo "nft not found"
  echo "install nftables and try again"
  exit 1
fi

if ! command -v perl
then
  echo "perl not found"
  echo "install perl and try again"
  exit 1
fi


for file in blacklistd consolidate_blacklist
do
    unlink /usr/local/bin/$file
    cp bin/$file /usr/local/bin
    chown root.root /usr/local/bin/$file
    chmod 0755 /usr/local/bin/$file
done

if [ ! -d /usr/local/etc/blacklist ]; then
    mkdir /usr/local/etc/blacklist
fi
chown logsurfer.logsurfer /usr/local/etc/blacklist
chmod 0755 /usr/local/etc/blacklist

cp conf/blacklistd.conf /usr/local/etc/blacklist
chown root.root /usr/local/etc/blacklist/blacklistd.conf
chmod 0644 /usr/local/etc/blacklist/blacklistd.conf

if [ ! -d /usr/local/etc/logsurfer ]; then
    mkdir /usr/local/etc/logsurfer
fi
chown logsurfer.logsurfer /usr/local/etc/logsurfer
chmod 0755 /usr/local/etc/logsurfer

for file in logsurfer/*
do
    file=$(basename $file)
    cp logsurfer/$file /usr/local/etc/logsurfer
    chown logsurfer.logsurfer /usr/local/etc/logsurfer/$file
    chmod 0644 /usr/local/etc/logsurfer/$file
done

if [ ! -d /usr/local/data/blacklist ]; then
    mkdir -p /usr/local/data/blacklist
fi
chown logsurfer.logsurfer /usr/local/data/blacklist
chmod 0755 /usr/local/data/blacklist

if [ ! -d /usr/local/etc/nftables.d ]; then
    mkdir -p /usr/local/etc/nftables.d
fi
chown root.root /usr/local/etc/nftables.d
chmod 0755 /usr/local/etc/nftables.d

touch /usr/local/etc/nftables.d/blacklist.nft
chown logsurfer.logsurfer /usr/local/etc/nftables.d/blacklist.nft
chmod 0644 /usr/local/etc/nftables.d/blacklist.nft


for file in systemd/*
do
    file=$(basename $file)
    cp systemd/$file /etc/systemd/system
    chown root.root /etc/systemd/system/$file
    chmod 0644 /etc/systemd/system/$file
    systemctl enable $file
    systemctl start $file
done

#cp iptablesload /etc/network/if-pre-up.d
#chown root.root /etc/network/if-pre-up.d/iptablesload
#chmod 0744 /etc/network/if-pre-up.d/iptablesload

cp log_dropped_packets /etc/cron.hourly
chown root.root /etc/cron.hourly/log_dropped_packets
chmod 0755 /etc/cron.hourly/log_dropped_packets

echo "ensure nftables has set blacklist in table filter"
