#!/bin/sh

#ipset restore </etc/ipset-blacklist/ip-blacklist.restore
ipset create blacklist2 -exist hash:ip
#ipset create whitelist -exist hash:ip
iptables-restore </usr/local/etc/iptables/rules_ip4
ip6tables-restore </usr/local/etc/iptables/rules_ip6
