#!/usr/bin/perl
#
use strict;
use warnings;
use Getopt::Long qw(:config bundling);
use Data::Dumper::Concise;
use Sys::Syslog;

my $data = `/usr/sbin/iptables -Z -v -n -x -L INPUT`;

my $packets = 0;
my $bytes = 0;
foreach my $line (split(/\n/, $data)) {
    if($line =~ m/^\s*(\d+)\s+(\d+)\s+(LOG_)?DROP/) {
        $packets += $1;
        $bytes += $2;
    }
}

openlog('iptables dropped', 'ndelay,nofatal,pid', 'local0');
syslog('info', '%s', "Dropped $packets packets / $bytes bytes");
